### ISSUE TITLE
[Issue] Cannot add the School

### ISSUE THREAD

**Issue by AgarwalSugandha** [WhiteflagProtocol/whiteflag-schoolpilot#13]
Adding a school gives "Something went wrong"

Steps to reproduce:
- Login to Whiteflag app
- enter your coordinates
- click on "Add icon"
- - fill in all the mandatory details and leave option field "Group" Blank
- click save
Outcome: error message is thrown

expected: The school should be saved

![image](https://github.com/WhiteflagProtocol/whiteflag-schoolpilot/assets/81156180/09e2397d-1b7d-4295-8ea9-609e53fe8d3c)

**Comment by Romulus10** [comment]
I think from what I was hearing this issue is resolved - is that the case?

**Comment by AgarwalSugandha** [comment]
yes thats correct, closing the issue
