### ISSUE TITLE
[Observation] Cancel edit-location

### ISSUE THREAD

**Issue by Bramwal** [WhiteflagProtocol/whiteflag-schoolpilot#19]

**Comment by Bramwal** [comment]
When creating an account it does not send out a confirmation to the corresponding mail-adress.

Steps to reproduce:

- Open whiteflag.fennellabs.com
- "create account"
- fill in username (Without spaces), mailadress and password
- press "create account"

**Comment by Romulus10** [comment]
Hi @Bramwal - do these notes go with this issue? I'm not sure what Cancel edit-location refers to.

**Comment by Bramwal** [comment]
Hi @Romulus10, I actually wanted to delete this issue because I found out that it was a fault on my behalf during testing. However I didn't manage to delete the issue myself

**Comment by Bramwal** [comment]
**Closed Issue because it was a mistake that should be deleted**
